#include "GameHeader.h"

const string GD::QQ_MAIL_SERVER_IP = "123.60.211.177";
const string GD::LOGIN_GATE_IP = "123.60.211.177";

const string GD::MONSTER_DROP_PATH = FrameDefine::MEDIA_PATH + "MonsterDrop/";
const string GD::DROP_PACKAGE_PATH = MONSTER_DROP_PATH + "Package/";
const string GD::DROP_LIST_PATH = MONSTER_DROP_PATH + "DropList/";
Array<GD::DIE_DROP_PACK_COUNT, int> GD::DIE_DROP_PACK_COUNT_LIST{ 1, 2, 3 };
Array<GD::DIE_DROP_DRESS_COUNT, int> GD::DIE_DROP_DRESS_COUNT_LIST{ 1, 2 };
Array<GD::DIE_DROP_PACK_COUNT, float> GD::DIE_DROP_PACK_ODDS_LIST{ 0.6f, 0.3f, 0.1f };
Array<GD::DIE_DROP_DRESS_COUNT, float> GD::DIE_DROP_DRESS_ODDS_LIST{ 0.8f, 0.2f };
Array<10, int> GD::WEAPON_CONSECRATION_BUFF{ 1042, 1050, 1058, 1066, 1074, 1082, 1090, 1098, 1106, 1114 };
HashMap<CHARACTER_PROPERTY, PROPERTY_VALUE_TYPE> GD::PROPERTY_VALUE_TYPE_MAP
{
	{ CHARACTER_PROPERTY::HP, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MAX_HP, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MP, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MAX_MP, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MIN_PHYSICS_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MAX_PHYSICS_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MIN_MAGIC_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MAX_MAGIC_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MIN_SORCERY_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MAX_SORCERY_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MIN_PHYSICS_DEFENCE, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MAX_PHYSICS_DEFENCE, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MIN_MAGIC_DEFENCE, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MAX_MAGIC_DEFENCE, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::ATTACK_SPEED, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::MOVE_SPEED, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::HIT_PROBABILITY, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::EVADE_PROBABILITY, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::CRITICAL_PROBABILITY, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::CRITICAL_DAMAGE_RATE, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::DECREASE_DAMAGE_RATE, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::INCREASE_DAMAGE_RATE, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::CRIME, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::LUCKY, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::HP_RECOVER, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MP_RECOVER, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::PHYSICS_DECREASE, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::MAGIC_DECREASE, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::SORCERY_DECREASE, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::DIG_MINE_SPEED, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::SKILL_ATTACK_INCREASE, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::ANTI_CRITICAL, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::COUNTER_ATTACK, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::COUNTER_PHYSICS_ATTACK, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::COUNTER_MAGIC_ATTACK, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::COUNTER_SORCERY_ATTACK, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::PACK_MAX_WEIGHT, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::NO_DEFENCE_PHYSICS_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::NO_DEFENCE_MAGIC_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::NO_DEFENCE_SORCERY_ATTACK, PROPERTY_VALUE_TYPE::INT },
	{ CHARACTER_PROPERTY::MONSTER_EXP_MULTI, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::SKILL_EXP_MULTI, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::PICK_GOLD_MULTI, PROPERTY_VALUE_TYPE::FLOAT },
	{ CHARACTER_PROPERTY::PICK_GOLD_INGOT_MULTI, PROPERTY_VALUE_TYPE::FLOAT },
};

HashMap<int, int> GD::DIG_MINE_ODDS
{
	{ 0, 250 },
	{ 1, 370 },
	{ 2, 20 },
	{ 3, 140 },
	{ 4, 70 },
	{ 5, 65 },
	{ 50, 4 },
	{ 200, 1 },
};

HashMap<int, int> GD::MINE_ID_ODDS
{
	{ 50016, 20 },		// 铜矿
	{ 50017, 20 },		// 铁矿
	{ 50018, 20 },		// 银矿
	{ 50062, 20 },		// 黑铁矿石,不可交易
	{ 50019, 10 },		// 金矿
	{ 50020, 7 },		// 黑铁原石,可交易
	{ 50021, 2 },		// 绿宝石矿
	{ 50022, 1 },		// 紫水晶矿
};

HashMap<float, int> GD::NPC_SELL_RATIO_ODDS
{
	{ 1.1f, 101 },
	{ 1.2f, 102 },
	{ 1.3f, 103 },
	{ 1.4f, 104 },
	{ 1.5f, 105 },
	{ 1.6f, 106 },
	{ 1.7f, 107 },
	{ 2.3f, 30 },
	{ 2.4f, 20 },
	{ 3.0f, 10 },
};

HashMap<int, float> GD::COMPOSITE_STAR_EQUIP_ODDS
{
	{1, 0.6f},
	{2, 0.5f},
	{3, 0.35f},
	{4, 0.2f},
};

HashMap<int, int> GD::COMPOSITE_STAR_EQUIP_GOLD
{
	{1, 300 * 10000},
	{2, 550 * 10000},
	{3, 1400 * 10000},
	{4, 2500 * 10000},
};

HashMap<int, int> GD::EQUIP_EXTRA_ATTACK_ODDS
{
	{ 1, 250 },
	{ 2, 230 },
	{ 3, 230 },
	{ 4, 80 },
	{ 5, 70 },
	{ 6, 70 },
	{ 7, 30 },
	{ 8, 20 },
	{ 9, 15 },
	{ 10, 5 },
};

HashMap<int, int> GD::SPECIAL_RING_LIST
{
	{ 30123, 2 },	// 传送戒指
	{ 30124, 2 },	// 麻痹戒指
	{ 30125, 2 },	// 复活戒指
	{ 30126, 28 },	// 火焰戒指
	{ 30127, 29 },	// 防御戒指
	{ 30128, 2 },	// 护身戒指
	{ 30129, 35 }	// 超负载戒指
};

HashMap<int, float> GD::COMPOSITE_SPECIAL_RING
{
	{ 1, 0.0f },
	{ 2, 0.0f },
	{ 3, 0.01f },
	{ 4, 0.05f },
	{ 5, 0.1f }
};

HashMap<int, int> GD::GUILD_ITEM_CONTRIBUTE
{
	{ 50024, 10000 },		// 祖玛头像
	{ 50077, 20000 },		// 祖玛酒酿
	{ 50078, 30000 },		// 祖玛玉露
};

HashMap<int, int> GD::GUILD_ITEM_EXP
{
	{ 50024, 1 },			// 祖玛头像
	{ 50077, 2 },			// 祖玛酒酿
	{ 50078, 5 },			// 祖玛玉露
};

Array<GD::TEAM_MEMBER, float> GD::TEAM_EXP_RATIO{ 1.0f, 0.6f, 0.5f, 0.45f, 0.42f, 0.4f };

HashMap<int, int> GD::BLESS_EQUIP_ODDS
{
	{ -1, 5 },
	{ 0, 3 },
	{ 1, 2 },
};

HashMap<int, int> GD::ENTER_FAIRY_LAND_ITEM
{
	{ 50022, 10 },			// 紫水晶矿
	{ 50021, 10 }			// 绿宝石矿
};

HashMap<MONSTER_STRENGTH, Vector2Int> GD::MONSTER_PROFICIENCY
{
	{ MONSTER_STRENGTH::NORMAL, Vector2Int(1, 1) },
	{ MONSTER_STRENGTH::ELITE, Vector2Int(6, 10) },
	{ MONSTER_STRENGTH::BOSS, Vector2Int(30, 50) },
	{ MONSTER_STRENGTH::SPECIAL, Vector2Int(50, 80) }
};

Vector<int> GD::HEI_AN_DA_DIAN_PK_SCORE { 50, 110, 180, 270 };
Vector<int> GD::HEI_AN_DA_DIAN_MAP_ID{ 583, 584, 585, 586 };
Vector<int> GD::WU_JIN_JIAN_TA_ITEM{ 50100, 50101, 50102, 50103, 50104, 50105, 50106, 50107, 50108 };