#include "GameHeader.h"

void GameSTLPoolRegister::registeAll()
{
	// 自定义类型
	mVectorPoolManager->registeVectorPool<FriendInfo>();
	mVectorPoolManager->registeVectorPool<Guild*>();
	mVectorPoolManager->registeVectorPool<GuildMemberInfo>();
	mVectorPoolManager->registeVectorPool<MonsterDrop*>();
	mVectorPoolManager->registeVectorPool<ObjectItemEquip*>();
	mVectorPoolManager->registeVectorPool<ObjectItemBox*>();
	mVectorPoolManager->registeVectorPool<ObjectItemConsumable*>();
	mVectorPoolManager->registeVectorPool<ObjectItemSkillBook*>();
	mVectorPoolManager->registeVectorPool<ObjectItemMaterial*>();
	// SQLite数据类型
	mVectorPoolManager->registeVectorPool<TDAchivement*>();
	mVectorPoolManager->registeVectorPool<TDAnimation*>();
	mVectorPoolManager->registeVectorPool<TDBuff*>();
	mVectorPoolManager->registeVectorPool<TDBuffDetail*>();
	mVectorPoolManager->registeVectorPool<TDCardPoolOrange*>();
	mVectorPoolManager->registeVectorPool<TDCondition*>();
	mVectorPoolManager->registeVectorPool<TDConditionDetail*>();
	mVectorPoolManager->registeVectorPool<TDEffect*>();
	mVectorPoolManager->registeVectorPool<TDEnvironment*>();
	mVectorPoolManager->registeVectorPool<TDEnvironmentSkill*>();
	mVectorPoolManager->registeVectorPool<TDEquipConsecration*>();
	mVectorPoolManager->registeVectorPool<TDEquipDecompose*>();
	mVectorPoolManager->registeVectorPool<TDEquipDecomposeFashion*>();
	mVectorPoolManager->registeVectorPool<TDEquipDecomposeSpecific*>();
	mVectorPoolManager->registeVectorPool<TDEquipStrength*>();
	mVectorPoolManager->registeVectorPool<TDEquipSuit*>();
	mVectorPoolManager->registeVectorPool<TDGlobal*>();
	mVectorPoolManager->registeVectorPool<TDGoods*>();
	mVectorPoolManager->registeVectorPool<TDGuild*>();
	mVectorPoolManager->registeVectorPool<TDGuildSalary*>();
	mVectorPoolManager->registeVectorPool<TDGuildTerritory*>();
	mVectorPoolManager->registeVectorPool<TDImagePositionAnimation*>();
	mVectorPoolManager->registeVectorPool<TDItem*>();
	mVectorPoolManager->registeVectorPool<TDItemBox*>();
	mVectorPoolManager->registeVectorPool<TDItemCard*>();
	mVectorPoolManager->registeVectorPool<TDItemConsumable*>();
	mVectorPoolManager->registeVectorPool<TDItemEquip*>();
	mVectorPoolManager->registeVectorPool<TDItemMaterial*>();
	mVectorPoolManager->registeVectorPool<TDItemSkillBook*>();
	mVectorPoolManager->registeVectorPool<TDMakeItem*>();
	mVectorPoolManager->registeVectorPool<TDMineRegion*>();
	mVectorPoolManager->registeVectorPool<TDMission*>();
	mVectorPoolManager->registeVectorPool<TDModelEquip*>();
	mVectorPoolManager->registeVectorPool<TDMonster*>();
	mVectorPoolManager->registeVectorPool<TDMonsterRegion*>();
	mVectorPoolManager->registeVectorPool<TDMonsterSkill*>();
	mVectorPoolManager->registeVectorPool<TDMonsterTemplate*>();
	mVectorPoolManager->registeVectorPool<TDMonsterWar*>();
	mVectorPoolManager->registeVectorPool<TDNPC*>();
	mVectorPoolManager->registeVectorPool<TDNPCConversation*>();
	mVectorPoolManager->registeVectorPool<TDNPCTransfer*>();
	mVectorPoolManager->registeVectorPool<TDPKArena*>();
	mVectorPoolManager->registeVectorPool<TDPlayerLevel*>();
	mVectorPoolManager->registeVectorPool<TDPlayerSkill*>();
	mVectorPoolManager->registeVectorPool<TDPlayerSkillDetail*>();
	mVectorPoolManager->registeVectorPool<TDReward*>();
	mVectorPoolManager->registeVectorPool<TDSceneCopy*>();
	mVectorPoolManager->registeVectorPool<TDSceneMap*>();
	mVectorPoolManager->registeVectorPool<TDSceneMapFile*>();
	mVectorPoolManager->registeVectorPool<TDSceneMapPeaceArea*>();
	mVectorPoolManager->registeVectorPool<TDSceneMapSubRegion*>();
	mVectorPoolManager->registeVectorPool<TDSceneMapTransfer*>();
	mVectorPoolManager->registeVectorPool<TDSkillBullet*>();
	mVectorPoolManager->registeVectorPool<TDTalkBubble*>();
	mVectorPoolManager->registeVectorPool<TDTalkBubbleGroup*>();
	mVectorPoolManager->registeVectorPool<TDTalkDialog*>();
	mVectorPoolManager->registeVectorPool<TDTriggerEvent*>();
	mVectorPoolManager->registeVectorPool<TDTriggerModifier*>();
	mVectorPoolManager->registeVectorPool<TDTriggerPoint*>();
	mVectorPoolManager->registeVectorPool<TDWuJinJianTa*>();
}